name: RueCi

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Install dependencies
      run: |
        rustup add clippy
        cargo install cargo-fmt

    - name: Format code
      run: |
        cargo fmt --all -- --check

    - name: Lint code
      run: |
        cargo clippy -- -D warnings

    - name: Build code
      run: |
        cargo build --release 
