# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy docs

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    container: rust:lastest
    steps:
      - name: Build with Cargo
        uses: actions/checkout@master
      - run: cargo doc --no-deps
      - run: rm -rf ./docs
      - run: echo "<meta http-equiv=\"refresh\" content=\"0; url=build_wheel\">" > target/doc/index.html
      - run: cp -r target/doc ./docs
